name: Slendercase
favicon: null
layout_spectrum: 0.34370255609974265
typography_spectrum: 0.4756150406319648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7564938620198518
  lightness: 0.38275004806928337
  saturation: 0.9496271733660251
  rhythmicContrast: 0.43035583128221333
purpose: []
