name: Slendercase
favicon: null
layout_spectrum: 0.34370255609974265
typography_spectrum: 0.4756150406319648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b3c1c2'
    - '#000000'
    - '#5f848a'
    - '#243536'
  brandStrength: 0.8125
  lightness: 0.38275004806928337
  saturation: 0.9496271733660251
  rhythmicContrast: 0.43035583128221333
purpose: []
